server:
  port: 8085

spring:
  application:
    name: coreapi-gateway
  cloud:
    gateway:
      routes:
        - id: coreapi-auth
          uri: http://localhost:8081/
          predicates:
            - Path=/auth/api/v1/auth/**
            - Method=POST
          filters:
            - name: LoggingGlobalFilter
              args:
                order: -1 # Set the order of the filter
