# docker-build.yml

name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Verify Maven build
        uses: .github/workflows/ci-flow.yml@v1.0.0

      - name: Set Docker image tag with Maven version
        id: set_docker_tag
        run: |
          DOCKER_TAG=${{ secrets.DOCKER_USERNAME }}/coreapi-gateway:${{ steps.get_version.outputs.version }}
          echo "Setting Docker image tag to: $DOCKER_TAG"
          echo "::set-output name=docker_tag::$DOCKER_TAG"

      - name: Use Docker image tag in subsequent steps
        run: |
          echo "Docker image tag is: ${{ steps.set_docker_tag.outputs.docker_tag }}"
        # Use this tag in your Docker build and push steps
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ steps.append_version.outputs.docker_tag }}
            ${{ secrets.DOCKER_USERNAME }}/coreapi-gateway:latest
          load: false
          no-cache: false
          pull: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
