

name: Java CI with Maven

on:
  workflow_dispatch

env:
  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64
  JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64

jobs:
  setup_jdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
  update_version:
    runs-on: ubuntu-latest
    #condition to check if build successful
    needs: setup_jdk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Increment version in pom.xml
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          next_version=$(echo $current_version | awk -F'[.-]' '{print $1"."$2"."$3+1}')
          echo "Current version: $current_version"
          echo "Next version: $next_version"
          mvn versions:set -DnewVersion=$next_version -DgenerateBackupPoms=false
          git config --global user.email ${{secrets.GIT_EMAIL}}
          git config --global user.name ${{secrets.GIT_USERNAME}}
          git add pom.xml
          git commit -m "Bump version to $next_version"
          echo "next_version=$next_version" >> $GITHUB_ENV
          git push origin HEAD:master
